=== Polpetta/xml-glossary/schema.xsd
<?xml version="1.0"?>
<xs:schema  targetNamespace="glossary"
            xmlns:xs="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified">
    <xs:element name="glossary">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="term" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="word" type="xs:ID" />
                            <xs:element name="plural" type="xs:string" minOccurs="0" />
                            <xs:element name="extended" type="xs:string" minOccurs="0" />
                            <xs:element name="definition" type="xs:string" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Polpetta/xml-glossary/glossary.xml
<?xml version="1.0" encoding="UTF-8"?>
<glossary   xmlns="glossary"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="schema.xsd">
    <term>
        <word>MaaS</word>
        <extended>MongoDB as an Admin Service</extended>
        <definition>Progetto</definition>
    </term>
    <term>
        <word>Prova</word>
        <definition>Definizione di prova</definition>
    </term>
    <term>
        <word>Multiple</word>
        <extended>Parola con definizioni multiple</extended>
        <definition>Definizione 1</definition>
        <definition>Definizione 2</definition>
        <definition>Definizione 3</definition>
    </term>
</glossary>
